# Generated by Django 5.0.4 on 2024-04-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('file', models.FileField(upload_to='uploads/form_templates/')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('file', models.FileField(blank=True, upload_to='uploads/forms/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='fields',
            field=models.ManyToManyField(blank=True, to='forms.formtemplatefield'),
        ),
    ]
